### ISSUE TITLE
`NoClassDefFoundError` after upgrading to 1.19.0-rc.2

### ISSUE THREAD

**Issue by JordanLongstaff** [szpak/gradle-pitest-plugin#385]
Ever since I upgraded from Pitest Gradle plugin version `1.19.0-rc.1` to `rc.2`, Pitest is consistently failing in my repo's CI workflow. It works just fine locally, but for some reason, in the CI workflow, it throws a `NoClassDefFoundError` because apparently it can't find a definition for a class that is declared in another module, which is a dependency of the module running Pitest. Details [here](https://github.com/JordanLongstaff/ArtemisAgent/actions/runs/18293547947/job/52093581614).

I know it's not a problem with Pitest itself because I declare the Pitest version explicitly (latest version) for all modules that use it. I don't see how it could be a problem with the Gradle wrapper, which makes me think #382 somehow caused it. Those are the only changes in `rc.2`, according to the changelog.

**Comment by JordanLongstaff** [comment]
I'm using [this PR](https://github.com/JordanLongstaff/ArtemisAgent/pull/421) to experiment with what seems to be a workaround, adding the modules as `pitest` dependencies. If that's now a requirement, it's a breaking change.

**Comment by szpak** [comment]
All the changes in this release:
https://github.com/szpak/gradle-pitest-plugin/compare/release/1.19.0-rc.1...release/1.19.0-rc.2

**Comment by szpak** [comment]
Thanks for your analysis @luisgomez29. I completely missed your reply... I will think over how to include it in README in the clear way.

**Comment by Vampire** [comment]
@luisgomez29 I fear I have to totally disagree with your analysis, and your solution is just working because of a side-effect.
There is no different behavior or encapsulation of configurations with CC or similar.

The difference why it fails on CI but works locally is simply because you are not running clean builds locally.

With your `pitest ...` lines you added those dependencies to the pitest launch classpath where they have nothing to do and just pollute the classpath.
The sideeffect of doing so is, that you also have the missing task dependency to the jar tasks building those dependencies.

When you run locally, you already have the jars available so it works.
On CI you run clean build and the jars are not built because of missing task dependencies.

So this clearly **is** a bug of this plugin, as it somewhere looses important implicit task dependencies.

**Comment by szpak** [comment]
Interesting 🤔  . Thank you @Vampire for your contribution! I will try to release RC.3 "soon" to have it tested by Jordan.

**Comment by Vampire** [comment]
I tested the changes with the exact commit of the project he linked to above. :-)
